# Generated by Django 5.0.14 on 2025-11-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_message_replies_reactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('system', 'System')], default='text', max_length=16),
        ),
    ]
