# Generated by Django 5.0.14 on 2025-11-21 18:59

import django.db.models.deletion
import libs.idgen
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigIntegerField(default=libs.idgen.generate_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('non_binary', 'non_binary'), ('other', 'other'), ('prefer_not_to_say', 'prefer_not_to_say')], max_length=32)),
                ('orientation', models.CharField(blank=True, choices=[('hetero', 'hetero'), ('homo', 'homo'), ('bi', 'bi'), ('pan', 'pan'), ('asexual', 'asexual'), ('other', 'other'), ('prefer_not_to_say', 'prefer_not_to_say')], max_length=32)),
                ('relationship_goal', models.CharField(choices=[('casual', 'casual'), ('long_term', 'long_term'), ('marriage', 'marriage'), ('unsure', 'unsure')], default='unsure', max_length=32)),
                ('values', models.JSONField(blank=True, default=list)),
                ('preferred_lifestyle', models.JSONField(blank=True, default=list)),
                ('attachment_style', models.CharField(blank=True, choices=[('secure', 'secure'), ('anxious', 'anxious'), ('avoidant', 'avoidant'), ('mixed', 'mixed')], max_length=32)),
                ('love_language', models.JSONField(blank=True, default=list)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_time', models.TimeField(blank=True, null=True)),
                ('birth_city', models.CharField(blank=True, max_length=128)),
                ('birth_country', models.CharField(blank=True, max_length=128)),
                ('birth_timezone', models.CharField(blank=True, max_length=64)),
                ('birth_latitude', models.FloatField(blank=True, null=True)),
                ('birth_longitude', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='profile_use_user_id_ae335e_idx')],
            },
        ),
    ]
