# Generated by Django 5.0.14 on 2025-11-02 06:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # 0001_initial already creates Subscription.user, Wallet.user, and unique_together.
    # Keeping this migration as a no-op prevents duplicate column errors on fresh DBs.
    operations = []
