# Generated by Django 5.0.14 on 2025-11-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="external_price_id",
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="external_customer_id",
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="external_subscription_id",
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
        migrations.AddField(
            model_name="wallet",
            name="external_customer_id",
            field=models.CharField(blank=True, max_length=96, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("canceled", "Canceled"),
                    ("incomplete", "Incomplete"),
                    ("past_due", "Past Due"),
                ],
                default="incomplete",
                max_length=16,
            ),
        ),
    ]
