# Generated by Django 5.0.14 on 2026-01-18 07:43

import apps.payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_checkout_and_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcheckout',
            name='reference',
            field=models.CharField(default=apps.payments.models.generate_payment_reference, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('ipay', 'iPay')], max_length=32),
        ),
    ]
