# Generated by Django 5.0.14 on 2026-01-18 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_paymentcheckout_reference_and_more'),
        ('payments', '0007_btcpay_provider_reference'),
    ]

    operations = [
    ]
