# Generated by Django 5.0.14 on 2026-01-24 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_merge_20260118_1257'),
        ('payments', '0010_gifttype_fields'),
    ]

    operations = [
    ]
