# Generated by Django 5.0.14 on 2026-01-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_merge_0008_merge_20260118_1257_0010_gifttype_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentevent',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('ipay', 'iPay'), ('btcpay', 'BTCPay'), ('apple_iap', 'Apple IAP'), ('google_iap', 'Google IAP')], max_length=32),
        ),
    ]
