# Generated by Django 5.0.14 on 2026-01-25 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_seed_test_gift'),
        ('payments', '0012_alter_paymentevent_provider'),
    ]

    operations = [
    ]
