# Generated by Django 5.0.14 on 2026-01-26 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_merge_20260125_0352'),
        ('payments', '0013_seed_gift_effects'),
    ]

    operations = [
    ]
