# Generated by Django 5.0.14 on 2026-01-26 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_gifttype_media_files'),
        ('payments', '0014_merge_0013_merge_20260125_0352_0013_seed_gift_effects'),
    ]

    operations = [
    ]
