# Generated by Django 5.0.14 on 2026-01-26 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_gifttype_url_charfields'),
        ('payments', '0015_merge_20260126_1809'),
    ]

    operations = [
    ]
