# Generated by Django 5.0.14 on 2026-01-27 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_merge_20260126_1836'),
        ('payments', '0016_normalize_gift_effects_v2'),
    ]

    operations = [
    ]
