# Generated by Django 5.0.14 on 2026-02-09 04:23

import apps.payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_seed_trendy_gifts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcheckout',
            name='reference',
            field=models.CharField(default=apps.payments.models.generate_payment_reference, max_length=64, unique=True),
        ),
    ]
