# Generated by Django 5.0.14 on 2026-01-28 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_merge_20260127_1720'),
        ('payments', '0017_seed_trendy_gifts'),
    ]

    operations = [
    ]
