# Generated by Django 5.0.14 on 2026-02-09 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_merge_0017_merge_20260127_1720_0017_seed_trendy_gifts'),
        ('payments', '0019_repair_gift_types'),
    ]

    operations = [
    ]
