# Generated by Django 5.0.14 on 2025-11-22 16:59

import django.db.models.deletion
import django.utils.timezone
import libs.idgen
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0003_mentormemory'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorsession',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mentorsession',
            name='language',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='mentorsession',
            name='mode',
            field=models.CharField(default='default', max_length=32),
        ),
        migrations.AddField(
            model_name='mentorsession',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='MentorMessage',
            fields=[
                ('id', models.BigIntegerField(default=libs.idgen.generate_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('mentor', 'Mentor')], max_length=16)),
                ('content', models.TextField()),
                ('meta', models.JSONField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mentor.mentorsession')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
