# Generated by Django 5.0.14 on 2025-11-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentor", "0004_mentorsession_active_mentorsession_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorsession",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
