# Generated by hand to align mentor models with new chat/streaming flow.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentor", "0005_mentorsession_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorsession",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mentorsession",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="mentormessage",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("assistant", "Assistant"), ("mentor", "Mentor")],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="mentorsession",
            name="answer",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="mentorsession",
            name="language",
            field=models.CharField(blank=True, default="en", max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name="mentorsession",
            name="mode",
            field=models.CharField(default="daily_mentor", max_length=32),
        ),
        migrations.AlterField(
            model_name="mentorsession",
            name="question",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="mentorsession",
            name="started_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
