# Generated by Django 5.0.14 on 2026-02-09 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_soulmatchresult'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='soulmatchresult',
            new_name='matching_so_pair_ke_a9bca2_idx',
            old_name='matching_soul_pai_2847a3_idx',
        ),
    ]
