# Generated by Django 5.0.14 on 2025-11-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers_and_more"),
        ("users", "0002_notification_settings"),
    ]

    operations = []
