# Generated by Django 5.0.14 on 2025-11-10 18:40

import django.db.models.deletion
import libs.idgen
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_merge_20251102_1653"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalMapProfile",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        default=libs.idgen.generate_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=120)),
                ("last_name", models.CharField(max_length=120)),
                ("birth_date", models.DateField()),
                ("birth_time", models.TimeField(blank=True, null=True)),
                ("birth_place_country", models.CharField(max_length=120)),
                ("birth_place_city", models.CharField(max_length=120)),
                (
                    "avatar_image",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_map",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
