# Generated by Django 5.0.14 on 2025-12-12 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userpii'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userpii',
            new_name='users_userp_email_4eeb07_idx',
            old_name='users_userp_email_8fda3f_idx',
        ),
    ]
