# Generated by Django 5.0.14 on 2025-11-20 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astro", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="birthdata",
            new_name="astro_birth_user_id_f706c3_idx",
            old_name="apps_astro_u_user_id_8a558b_idx",
        ),
        migrations.RenameIndex(
            model_name="natalchart",
            new_name="astro_natal_user_id_c05ba6_idx",
            old_name="apps_astro_u_user_id_2d8ad8_idx",
        ),
    ]
