# Generated by Django 5.0.14 on 2026-02-09 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0003_astrologyresult'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='astrologyresult',
            new_name='astro_astro_birth_d_66cf56_idx',
            old_name='astro_astro_birth_d_6b5a2f_idx',
        ),
    ]
