# Generated by Django 5.0.14 on 2026-01-18 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_action_0c0ad1_idx',
            old_name='audit_audit_action_82fd8d_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_object__0e78a5_idx',
            old_name='audit_audit_object__c9b0e7_idx',
        ),
    ]
