# Generated by Django 5.0.14 on 2025-12-12 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrib_rewards', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contributorprofile',
            new_name='contrib_rew_github__30cabc_idx',
            old_name='contrib_re_github__a562a7_idx',
        ),
        migrations.RenameIndex(
            model_name='payout',
            new_name='contrib_rew_snapsho_5d0c70_idx',
            old_name='contrib_re_snapsho_aa39e9_idx',
        ),
        migrations.RenameIndex(
            model_name='payout',
            new_name='contrib_rew_contrib_410774_idx',
            old_name='contrib_re_contribu_4d5990_idx',
        ),
        migrations.RenameIndex(
            model_name='rewardevent',
            new_name='contrib_rew_contrib_e20f93_idx',
            old_name='contrib_re_contribu_62a2aa_idx',
        ),
        migrations.RenameIndex(
            model_name='rewardevent',
            new_name='contrib_rew_event_t_52088b_idx',
            old_name='contrib_re_event_ty_71bfa1_idx',
        ),
    ]
