# Generated by Django 5.0.14 on 2026-01-18 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrib_rewards', '0003_rewardevent_ruleset_version'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ledgerentry',
            new_name='contrib_rew_account_142ee6_idx',
            old_name='contrib_re_account__77dc1d_idx',
        ),
        migrations.RenameIndex(
            model_name='ledgerentry',
            new_name='contrib_rew_tx_id_3a2921_idx',
            old_name='contrib_re_tx_id_abbde3_idx',
        ),
    ]
