# Generated by Django 5.0.14 on 2026-02-09 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_events_agreement_visibility'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='problemevent',
            new_name='community_p_problem_e1bfac_idx',
            old_name='community_p_prob_id_e6ab7b_idx',
        ),
        migrations.RenameIndex(
            model_name='problemevent',
            new_name='community_p_type_7ab0fe_idx',
            old_name='community_p_type_7f6b26_idx',
        ),
    ]
