# Generated by Django 5.0.14 on 2026-01-18 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_coinaccount_user_protect'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='coinaccount',
            new_name='coin_coinac_account_cfe299_idx',
            old_name='coin_acc_account_key_idx',
        ),
        migrations.RenameIndex(
            model_name='coinledgerentry',
            new_name='coin_coinle_account_425cea_idx',
            old_name='coin_led_account_key_created_at_idx',
        ),
    ]
