# Generated by Django 5.0.14 on 2026-02-03 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0003_paid_products_entitlements'),
        ('coin', '0003_rename_coin_acc_account_key_idx_coin_coinac_account_cfe299_idx_and_more'),
    ]

    operations = [
    ]
