# Generated by Django 5.0.14 on 2026-02-09 04:23

import libs.idgen
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0003_paid_products_entitlements'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='coinaccount',
            new_name='coin_coinac_account_cfe299_idx',
            old_name='coin_acc_account_key_idx',
        ),
        migrations.RenameIndex(
            model_name='coinledgerentry',
            new_name='coin_coinle_account_425cea_idx',
            old_name='coin_led_account_key_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='userentitlement',
            new_name='coin_useren_user_id_756cde_idx',
            old_name='coin_usere_user_id_55b5b0_idx',
        ),
        migrations.AlterField(
            model_name='paidproduct',
            name='id',
            field=models.BigIntegerField(default=libs.idgen.generate_id, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userentitlement',
            name='id',
            field=models.BigIntegerField(default=libs.idgen.generate_id, editable=False, primary_key=True, serialize=False),
        ),
    ]
