# Generated by Django 5.0.14 on 2026-02-07 17:17

import libs.idgen
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0004_merge_20260203_0453'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userentitlement',
            new_name='coin_useren_user_id_756cde_idx',
            old_name='coin_usere_user_id_55b5b0_idx',
        ),
        migrations.AlterField(
            model_name='paidproduct',
            name='id',
            field=models.BigIntegerField(default=libs.idgen.generate_id, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userentitlement',
            name='id',
            field=models.BigIntegerField(default=libs.idgen.generate_id, editable=False, primary_key=True, serialize=False),
        ),
    ]
