# Generated by Django 5.0.14 on 2026-02-09 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0004_rename_coin_acc_account_key_idx_coin_coinac_account_cfe299_idx_and_more'),
        ('coin', '0005_rename_coin_usere_user_id_55b5b0_idx_coin_useren_user_id_756cde_idx_and_more'),
    ]

    operations = [
    ]
