# Generated by Django 5.0.14 on 2026-02-09 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_paid_reactions_and_likes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paidreaction',
            new_name='social_paid_target__815e20_idx',
            old_name='paidreaction_target_created_idx',
        ),
    ]
